version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    container_name: appPython
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    networks:
      - shared_network

  postgres:
    image: postgres
    container_name: postgres
    networks:
      - shared_network
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  shared_network:
    driver: bridge
    
volumes:
  postgres_data:
